import type { Category, Conversation, Message, Product } from "@/types";

export const categories: Category[] = [
  { id: "women", label: "Women" },
  { id: "men", label: "Men" },
  { id: "kids", label: "Kids" },
  { id: "accessories", label: "Accessories" },
  { id: "shoes", label: "Shoes" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Vintage Levi's 501 High Waisted Jeans",
    brand: "Levi's",
    price: 65,
    size: "M",
    condition: "Good",
    category: "Women",
    images: ["/vintage-levis-jeans-denim.jpg", "/jeans-back-pocket-detail.jpg", "/jeans-styling-outfit.jpg"],
    description:
      "Classic high-waisted 501 jeans in excellent vintage condition. Perfect fade and authentic wear patterns. Waist measures 28 inches.",
    seller: {
      id: "s1",
      name: "Sarah M.",
      avatar: "/smiling-woman-profile.png",
      rating: 4.8,
      responseTime: "< 2 hours",
      memberSince: "March 2023",
      itemsSold: 47,
      reviews: 42,
    },
  },
  {
    id: "2",
    title: "Nike Air Force 1 Low White",
    brand: "Nike",
    price: 89,
    size: "42",
    condition: "Like New",
    category: "Shoes",
    images: ["/nike-air-force-1-white-sneakers.jpg", "/white-sneakers-side-view.jpg"],
    description: "Worn only twice, practically new condition. Size EU 42 / US 8.5. Original box included.",
    seller: {
      id: "s2",
      name: "Mike T.",
      avatar: "/man-profile-photo-casual.jpg",
      rating: 4.9,
      responseTime: "< 1 hour",
      memberSince: "January 2022",
      itemsSold: 124,
      reviews: 118,
    },
  },
  {
    id: "3",
    title: "Zara Oversized Blazer Beige",
    brand: "Zara",
    price: 45,
    size: "S",
    condition: "Good",
    category: "Women",
    images: ["/beige-oversized-blazer-women.jpg"],
    description: "Beautiful oversized blazer perfect for layering. Minor pilling on interior, otherwise great condition.",
    seller: {
      id: "s3",
      name: "Emma L.",
      avatar: "/young-woman-profile.png",
      rating: 4.6,
      responseTime: "< 4 hours",
      memberSince: "August 2023",
      itemsSold: 15,
      reviews: 13,
    },
  },
  {
    id: "4",
    title: "Ralph Lauren Polo Shirt Navy",
    brand: "Ralph Lauren",
    price: 35,
    size: "L",
    condition: "Like New",
    category: "Men",
    images: ["/navy-ralph-lauren-polo-shirt.jpg"],
    description: "Classic navy polo in excellent condition. Logo embroidery intact, no fading.",
    seller: {
      id: "s4",
      name: "James K.",
      avatar: "/man-profile-professional.jpg",
      rating: 4.7,
      responseTime: "< 3 hours",
      memberSince: "May 2022",
      itemsSold: 89,
      reviews: 85,
    },
  },
  {
    id: "5",
    title: "Gucci Marmont Belt Black",
    brand: "Gucci",
    price: 280,
    size: "85",
    condition: "Good",
    category: "Accessories",
    images: ["/gucci-marmont-belt-black-gold.jpg"],
    description:
      "Authentic Gucci Marmont belt with double G buckle. Light wear on hardware, leather in great shape. Size 85.",
    seller: {
      id: "s5",
      name: "Olivia R.",
      avatar: "/stylish-woman-profile.jpg",
      rating: 5.0,
      responseTime: "< 1 hour",
      memberSince: "December 2021",
      itemsSold: 203,
      reviews: 198,
    },
  },
  {
    id: "6",
    title: "H&M Kids Denim Jacket",
    brand: "H&M",
    price: 18,
    size: "8Y",
    condition: "Good",
    category: "Kids",
    images: ["/kids-denim-jacket-blue.jpg"],
    description: "Cute denim jacket for kids aged 7-8. Some fading from wash but adds to the look!",
    seller: {
      id: "s6",
      name: "Lisa P.",
      avatar: "/mother-profile-photo.jpg",
      rating: 4.5,
      responseTime: "< 6 hours",
      memberSince: "September 2023",
      itemsSold: 8,
      reviews: 7,
    },
  },
  {
    id: "7",
    title: "Adidas Originals Tracksuit",
    brand: "Adidas",
    price: 75,
    size: "M",
    condition: "Like New",
    category: "Men",
    images: ["/adidas-originals-tracksuit-black.jpg"],
    description: "Classic three stripe tracksuit. Jacket and pants set. Worn once for a photoshoot.",
    seller: {
      id: "s2",
      name: "Mike T.",
      avatar: "/man-profile-photo-casual.jpg",
      rating: 4.9,
      responseTime: "< 1 hour",
      memberSince: "January 2022",
      itemsSold: 124,
      reviews: 118,
    },
  },
  {
    id: "8",
    title: "Coach Crossbody Bag Tan",
    brand: "Coach",
    price: 120,
    size: "One Size",
    condition: "Good",
    category: "Accessories",
    images: ["/coach-tan-leather-crossbody-bag.jpg"],
    description: "Beautiful tan leather crossbody with adjustable strap. Minor scratches on hardware.",
    seller: {
      id: "s5",
      name: "Olivia R.",
      avatar: "/stylish-woman-profile.jpg",
      rating: 5.0,
      responseTime: "< 1 hour",
      memberSince: "December 2021",
      itemsSold: 203,
      reviews: 198,
    },
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "c1",
    user: { id: "s1", name: "Sarah M.", avatar: "/smiling-woman-profile.png" },
    lastMessage: "Hi! Is this still available?",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    unreadCount: 2,
    product: { id: "1", title: "Vintage Levi's 501", image: "/vintage-levis-jeans.jpg", price: 65 },
  },
  {
    id: "c2",
    user: { id: "s2", name: "Mike T.", avatar: "/man-profile-photo-casual.jpg" },
    lastMessage: "I can do $80 if you're interested",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unreadCount: 0,
    product: { id: "2", title: "Nike Air Force 1", image: "/classic-white-sneakers.png", price: 89 },
  },
  {
    id: "c3",
    user: { id: "s5", name: "Olivia R.", avatar: "/stylish-woman-profile.jpg" },
    lastMessage: "Just shipped! Tracking number is...",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unreadCount: 0,
    product: { id: "5", title: "Gucci Marmont Belt", image: "/gucci-belt.jpg", price: 280 },
  },
];

export const mockMessages: Message[] = [
  { id: "m1", senderId: "s1", text: "Hi! Is this still available?", timestamp: new Date(Date.now() - 1000 * 60 * 10), isOwn: false },
  { id: "m2", senderId: "me", text: "Yes it is! Are you interested?", timestamp: new Date(Date.now() - 1000 * 60 * 8), isOwn: true },
  { id: "m3", senderId: "s1", text: "Would you consider $55?", timestamp: new Date(Date.now() - 1000 * 60 * 5), isOwn: false },
];